---
name: start-release
description: Creates release branch, tag and updates version, updates next development version
inputs:
  github_token:
    description: "GitHub token of a user with permission to create a release"
    required: true
  version:
    required: true
    description: Release version
  update_version_command:
    required: false
    default: ""
    description: Command to update release version
runs:
  using: composite
  steps:
    - name: Setup git
      shell: bash
      run: |
        git config --global --add safe.directory /github/workspace
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
    - name: Create release branch
      shell: bash
      run: git checkout -b release/${{ inputs.version }}
    - name: Set release version
      shell: bash
      run: echo "VERSION=${{ inputs.version }}-rc1" >> $GITHUB_ENV
    - name: Update release version
      if: inputs.update_version_command != ''
      shell: bash
      run: ${{ inputs.update_version_command }}
    - name: Commit and push tag
      shell: bash
      run: |
        git add .
        git commit --allow-empty -a -m "Bump version to ${VERSION}"
        git tag -a v${VERSION} -m "Version ${VERSION}"
        git push origin release/${{ inputs.version }} --follow-tags
    - name: "Create PR to main"
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { repo, owner } = context.repo;
          github.rest.pulls.create({
            title: 'Release ${{ inputs.version }}',
            owner: owner,
            repo: repo,
            head: 'release/${{ inputs.version }}',
            base: 'main',
            body: '',
          });
