name: Complete Release

on:
  pull_request:
    types:
      - closed

env:
  pr_version: ${{ github.event.number }}
  tag_name: ${{ github.event.release.tag_name }}
jobs:
  if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ env.tag_name }}
            release_name: Release ${{ env.tag_name }}
            body: |
              PR: 
              - #${{ env.pr_version }}
              Changes in this Release:
              - Hey I did something
            draft: false
            prerelease: false