name: Complete Release

on:
  pull_request:
  workflow_dispatch:

env:
  pr_version: ${{ github.event.number }}
jobs:
  complete_release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dbaldree/github-actions-baldree/actions/complete-release@v0.1.2-rc1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            PR_VERSION: ${{ env.pr_version }}
            GITHUB_REPOSITORY: ${{ secrets.GITHUB_PATH }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 