name: Upload artifacts

on:
  workflow_dispatch:

env:
  dw_version: $GITHUB_REF

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: dbaldree/github-actions-baldree/actions/tar-release@v0.0.9-rc1
      with:
        directory: './artefacts'
        filename: 'cloud-cc-datawarehouse-postgres.tar.gz'
        exclusions: '*.git* /*node_modules/* .editorconfig *actions* README.md cloud-cc-datawarehouse-postgres.tar.gz'
  upload_artifact:
    name: Upload artifact to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbaldree/github-actions-baldree/actions/upload-artifacts-to-s3@v0.0.9-rc1
        with:
          artifacts: cloud-cc-datawarehouse-postgres.tar.gz
          s3_bucket: "baldrees-junk-bucket"
          s3_destination: "gitartifacts"
          aws_region: us-east-2
          aws_role_to_assume: "none"
          aws_role_session_name: "${{ github.repository }}-${{ github.workflow }}-${{ github.run_id }}"
          aws_role_duration_seconds: 900