name: Upload artifacts

on:
  workflow_dispatch:

#env:
#  dw_version: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Archive Release
      uses: dbaldree/github-actions-baldree/actions/tar-release@main
      with:
        directory: '.'
        filename: 'cloud-cc-datawarehouse-postgres.${{ steps.vars.outputs.tag }}.tar.gz'
        exclusions: '*.git* /*node_modules/* .editorconfig *actions* README.md cloud-cc-datawarehouse-postgres.${{ steps.vars.outputs.tag }}.tar.gz'
        release: '${{ steps.vars.outputs.tag }}'
  upload_artifact:
    needs: [build]
    name: Upload artifact to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbaldree/github-actions-baldree/actions/upload-artifacts-to-s3@main
        with:
          artifacts: cloud-cc-datawarehouse-postgres.tar.gz
          s3_bucket: "baldrees-junk-bucket"
          s3_destination: "gitartifacts"
          aws_region: us-east-2
          aws_role_to_assume: "none"
          aws_role_session_name: "${{ github.repository }}-${{ github.workflow }}-${{ github.run_id }}"
          aws_role_duration_seconds: 900
