name: Upload artifacts

on:
  push:
    branches:
      - $GITHUB_REF

env:
  dw_version: $GITHUB_REF

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
  upload_artifact:
    name: Upload artifact to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: advarra-engineering/action-advarra-workflows/actions/upload-artifacts-to-s3@v1
        with:
          artifacts: |
            target/my-artifact-*.jar
            path/to/other-artifact-*.jar
          s3_bucket: "${{ vars.CLOUD_DEV_ARTIFACTS_BUCKET }}"
          s3_destination: "${{ env.dw_version }}"
          aws_region: us-east-2
          aws_role_to_assume: ${{ secrets.CLOUD_DEV_PUBLISH_ROLE_TO_ASSUME }}
          aws_role_session_name: "${{ github.repository }}-${{ github.workflow }}-${{ github.run_id }}"
          aws_role_duration_seconds: 900