name: Upload artifacts

on:
  push:
    branches:
      - $GITHUB_REF

env:
  dw_version: $GITHUB_REF

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: dbaldree/github-actions-baldree/actions/tar-release@0.0.1
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
  upload_artifact:
    name: Upload artifact to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbaldree/github-actions-baldree/actions/upload-artifacts-to-s3@0.0.1
        with:
          artifacts: |
            target/my-artifact-*.jar
            path/to/other-artifact-*.jar
          s3_bucket: "baldrees-junk-bucket"
          s3_destination: "gitartifacts"
          aws_region: us-east-2
          aws_role_to_assume: "none"
          aws_role_session_name: "${{ github.repository }}-${{ github.workflow }}-${{ github.run_id }}"
          aws_role_duration_seconds: 900