name: Start Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version of new Release"
jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dbaldree/github-actions-baldree/actions/start-release@v0.1.4-rc1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          update_version_command: echo 123