name: Start Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version of new Release"
      next_dev_version:
        type: string
        required: false
        description: "Next development version"

jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADVARRA_ENGINEERING_ORG_TOKEN }}
      # other steps, like java setup
      - uses: advarra-engineering/action-advarra-workflows/actions/start-release@v1
        with:
          github_token: ${{ secrets.ADVARRA_ENGINEERING_ORG_TOKEN }}
          version: ${{ inputs.version }}
          update_version_command: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$VERSION
          # The following (updating next development version) is optional.
          next_dev_version: ${{ inputs.next_dev_version }}
          update_next_dev_version_command: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$NEXT_DEV_VERSION